#Ajoute une requête pour inscrire un utilisateur :
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "email": "q@q.com",
  "password": "123",
  "name": "Quentin",
  "age": 25
}

###

#Ajoute une requête pour se connecter et obtenir un token JWT:
POST http://localhost:8080/auth/login
Content-Type: application/json

{
"email": "q@q.com",
"password": "123"
}

###
#Pour accéder à une ressource protégée, on utilise le token obtenu à partir de la connexion :
GET http://localhost:8080/api/users
Authorization: Bearer <eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJxQHEuY29tIiwiaWF0IjoxNzI0MzIxNTk0LCJleHAiOjE3MjQ0MDc5OTR9.qzthUy51arAutEhvtiUAkRf290AmeyILVY7wjEQBwDcRlMPBejEMqLjo2QrWVDQuKKNsvUdoM6y7Obyb8pJ_vQ>
###
#Requetes CRUD
GET http://localhost:8080/api/users

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "test token",
  "age": 30
}

###

PUT http://localhost:8080/api/users/9
Content-Type: application/json

{
  "name": "Jane",
  "age": 35
}

###

DELETE http://localhost:8080/api/users/2